### PR TITLE
Fix certstore windows cmsg type error when building using go v1.18

### LINKED ISSUE #107: certstore: certstore_windows.go type error
After installing & importing the smimesign/certstore package, I get the following error while running my go main program:

..\..\go\pkg\mod\github.com\github\smimesign@v0.2.0\certstore\certstore_windows.go:640:29: cannot convert cmsg (variable of type *_Ctype_char) to type _Ctype_HANDLE

the only code I have added is the following:

	store, err := certstore.Open()
	if err != nil {
		fmt.Println(err)
	}
	defer store.Close()

Is there a way to fix this ?

### PR DESCRIPTION
**Pull request by ElMostafaIdrassi**
When trying to use `certstore` in a project that makes use of go v1.18+, the following error occurs : 

```
github.com\github\smimesign@v0.2.0\certstore\certstore_windows.go:640:29: cannot convert cmsg (variable of type *_Ctype_char) to type _Ctype_HANDLE
```

From this [golang issue](https://github.com/golang/go/issues/51726), it appears that go 1.18 has added some safety checks which reject unsafe conversions, resulting in such errors.

A simple fix is to cast the `cms` variable into an `unsafe.Pointer` before casting it to a `C.HLOCAL`.
This change was tested on Windows by building `smimesign` locally and running the test suite.

Closes #107

Signed-off-by: El Mostafa IDRASSI <mostafa.idrassi@tutanota.com>

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks for this PR!

It looks fairly straightforward — we'll have to verify and debug this a bit, but looks like an appropriate fix.

**Comment by pc-ahrens** [comment]
> Thanks for this PR!
> 
> It looks fairly straightforward — we'll have to verify and debug this a bit, but looks like an appropriate fix.

This pull requests also fixes an issue we have, that our signed commits cannot be verified with `git verify-commit <commitid>`. 
A misleading error message is shown: ```failed to verify signature: x509: certificate signed by unknown authority```

Is there are a roadmap or release date when a new release with this fix will be available?

**Comment by naggie** [comment]
I can confirm this is an issue on `go version go1.20.8 linux/amd64`

**Review by craigdfrench — APPROVED** [review]

**Comment by vcsjones** [comment]
Closing and re-opening to jog CI.

**Comment by vcsjones** [comment]
This pull request was cherry-picked in pull request #149. Thank you for your contribution! I am going to close this pull request since your commits are now merged.

**Pull request closed without merging**
